---
branches:
  only:
    - master

services:
  - docker

env:
  - distro: centos7
    init: /usr/sbin/init
    run_opts: "--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: jessie
    init: "/lib/systemd/systemd"
    run_opts: "--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: stretch
    init: ""
    run_opts: ""
  - distro: xenial
    init: /lib/systemd/systemd
    run_opts: "--privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro"

before_script:
  - >
    docker build --no-cache --pull -t graylog-ansible-role-${distro}
    -f tests/support/${distro}.Dockerfile tests/support

script:
  - >
    docker run -d -it -v $PWD:/role:ro
    ${run_opts} --name ${distro}
    graylog-ansible-role-${distro} ${init}
  - DOCKER_CONTAINER_ID=$(docker ps --filter name=${distro} -q)
  - >
    docker exec -it $DOCKER_CONTAINER_ID
    /bin/bash -xec "bash -x run-tests.sh"
