---
- name: Repositories should be updated
  yum:
    name: "{{ graylog_yum_rpm_url }}"
    state: present
    update_cache: True

- name: Graylog server should be installed
  yum:
    name: "{{ graylog_server_package }}"
    state: present
  notify: restart graylog-server
